#!/usr/bin/env python

import os
import sys
from pprint import pprint
from ruamel.yaml import YAML
import json

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
from dawnet.parser import dawnet
from dawnet.coala import dawnetcoala


def main():
    if len(sys.argv) > 1:
        if os.path.isfile(sys.argv[1]):
            with open(sys.argv[1]) as f:
                expr = f.read()
        else:
            expr = sys.argv[1]
    else:
        expr = sys.stdin.read()
    
    g_model = dawnet.parse_guard(expr)
    print(json.dumps(dawnet.guard_parse_tree(g_model)))
    guard = dawnet.check_guard(expr)
    rules = dawnetcoala.guard_to_rules('test', guard)
    # YAML().dump(guard, sys.stdout)
    print(guard.prefixExpr())
    pprint(rules)
    # pprint(guard)
    # YAML(typ='safe').dump(guard, sys.stdout)
    return 0


if __name__ == '__main__':
    sys.exit(main()) 